### ISSUE TITLE
Lab 1 (Data Analysis)

### ISSUE THREAD

**Issue by michael-camilleri** [JamesOwers/iaml2017#5]
I am not sure if the Q3 (a) is clear enough as to what to show? At first I expected that we were supposed to show the distribution of words by spam/ham?

**Comment by michael-camilleri** [comment]
Is there a reason we go for the Multinomial NB, given that we are dealing with binary data?
 **UPDATE**: They give the exact same results... the Documentation on Scikit learn is misleading...

**Comment by fimbrethiI** [comment]
Hi,

I think you have the wrong email address.

best,

Catherine

**Comment by michael-camilleri** [comment]
Q9: I am a bit of a stickler... but actually, it would be more accurate to say that we would need to estimate a full 55-variable joint distribution rather than a covariance matrix: i.e. a pmf with 2^55-1 entries. This is the most general case since 0 covariance does not imply conditional independence...

**Comment by fimbrethiI** [comment]
Please stop emailing me.

**Comment by michael-camilleri** [comment]
Q11: Solution. Should use loc instead of ix.

**Comment by michael-camilleri** [comment]
Incorrect Version
